FROM ubuntu:15.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y --no-install-recommends curl wget
RUN apt-get install -y --no-install-recommends unzip software-properties-common

CMD ["/bin/bash"]
